/**
 * Pinch Payments API client (SANDBOX ONLY — base is https://api.getpinch.com.au/test).
 *
 * Contract (hard-rule #4): every exported function returns
 * `T | StructuredError`. We NEVER throw a raw exception at a caller — network
 * failures, non-2xx responses, and JSON parse errors all come back as a
 * structured error object.
 *
 * Amounts are always integer cents and are passed straight through (Pinch is
 * natively in cents). We never touch account numbers except to mask them.
 */

import type { Env, StructuredError } from "./types";
import { isStructuredError } from "./types";
import { structuredError } from "./util";

// ── Pinch response shapes (only the fields we rely on) ───────────────────────

export interface PinchPayer {
  id: string;
  firstName?: string;
  lastName?: string;
  emailAddress?: string;
  sources?: PinchSource[];
  [k: string]: unknown;
}

export interface PinchSource {
  id: string;
  sourceType?: string;
  isAuthorised?: boolean;
  supportsRealtime?: boolean;
  [k: string]: unknown;
}

export interface PinchPayment {
  id: string;
  status?: string;
  amount?: number;
  dishonour?: unknown;
  /**
   * Pinch nests the payer under `payer.id` on list/get responses — there is NO
   * top-level `payerId`. Read the id via `payer.id`.
   */
  payer?: { id?: string; firstName?: string; lastName?: string; [k: string]: unknown };
  /** Full ISO datetime, e.g. "2026-06-22T14:00:00.0000000Z" — NOT a bare YYYY-MM-DD. */
  transactionDate?: string;
  description?: string;
  /** Present when this payment was generated by a Plan+Subscription, not a bare POST /payments. */
  subscription?: { id?: string; planId?: string; planName?: string };
  [k: string]: unknown;
}

export interface PinchEvent {
  id: string;
  type?: string;
  eventDate?: string;
  metadata?: unknown;
  [k: string]: unknown;
}

/** Wrapped list envelope used by /payments/scheduled, /events, /transfers/items. */
export interface PinchPage<T> {
  data: T[];
  page: number;
  pageSize: number;
  totalPages: number;
  totalItems: number;
}

// ── OAuth token cache ────────────────────────────────────────────────────────

interface CachedToken {
  access_token: string;
  /** epoch milliseconds at which the token expires */
  expires_at: number;
}

const TOKEN_KV_KEY = "pinch:token";
/** Refresh this many ms before the real expiry so in-flight calls never 401. */
const TOKEN_REFRESH_SKEW_MS = 60_000;

/**
 * The OAuth client_id.
 *
 * NOTE: client_id is the APPLICATION ID (app_...), NOT the publishable key
 * (pk_...) — Pinch's own docs wording is misleading here; verified against a
 * live sandbox 200. There is no dedicated PINCH_APPLICATION_ID binding, so we
 * store the Application ID in the PINCH_PUBLISHABLE_KEY secret. If auth 401s,
 * put the real app_... value there.
 */
function getClientId(env: Env): string {
  return env.PINCH_PUBLISHABLE_KEY;
}

/**
 * Return a valid bearer token, minting + caching a fresh one when the cached
 * token is missing or within the refresh skew of expiry.
 */
export async function getToken(env: Env): Promise<string | StructuredError> {
  try {
    const cached = (await env.TOKENS.get(TOKEN_KV_KEY, "json")) as CachedToken | null;
    if (cached && cached.expires_at - Date.now() > TOKEN_REFRESH_SKEW_MS) {
      return cached.access_token;
    }

    const body = new URLSearchParams({
      grant_type: "client_credentials",
      client_id: getClientId(env),
      client_secret: env.PINCH_SECRET_KEY,
    });

    const res = await fetch(env.PINCH_AUTH_URL, {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body,
    });

    const text = await res.text();
    let parsed: unknown;
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch {
      parsed = { raw: text };
    }

    if (!res.ok) {
      return structuredError("oauth_failed", "Pinch OAuth token request failed", {
        status: res.status,
        body: parsed,
      });
    }

    const token = parsed as {
      access_token?: string;
      expires_in?: number;
      token_type?: string;
    };
    if (!token.access_token) {
      return structuredError("oauth_failed", "OAuth response missing access_token", {
        body: parsed,
      });
    }

    const expiresInSec = typeof token.expires_in === "number" ? token.expires_in : 3600;
    const record: CachedToken = {
      access_token: token.access_token,
      expires_at: Date.now() + expiresInSec * 1000,
    };
    // TTL the KV entry to the token lifetime so a stale token never lingers.
    await env.TOKENS.put(TOKEN_KV_KEY, JSON.stringify(record), {
      expirationTtl: Math.max(60, expiresInSec),
    });

    return record.access_token;
  } catch (err) {
    return structuredError("network_error", "Failed to reach Pinch OAuth endpoint", {
      cause: String(err),
    });
  }
}

// ── error normalisation ──────────────────────────────────────────────────────

/**
 * Pinch returns errors in two different shapes depending on the endpoint:
 *   1. { errors: [{ message, field }] }
 *   2. bare array of { propertyName, errorMessage, ... }
 * Normalise BOTH into our StructuredError. The raw body is kept in `details`.
 */
function normalisePinchError(body: unknown, status: number): StructuredError {
  // Shape 2: bare array of { propertyName, errorMessage }
  if (Array.isArray(body)) {
    const messages = body
      .map((e) => {
        const item = e as { propertyName?: string; errorMessage?: string };
        if (item.errorMessage) {
          return item.propertyName
            ? `${item.propertyName}: ${item.errorMessage}`
            : item.errorMessage;
        }
        return null;
      })
      .filter((m): m is string => m !== null);
    return structuredError(
      "pinch_error",
      messages.length ? messages.join("; ") : `Pinch request failed (HTTP ${status})`,
      { status, body },
    );
  }

  // Shape 1: { errors: [{ message, field }] }
  if (body && typeof body === "object" && "errors" in body) {
    const errs = (body as { errors?: unknown }).errors;
    if (Array.isArray(errs)) {
      const messages = errs
        .map((e) => {
          const item = e as { message?: string; field?: string };
          if (item.message) {
            return item.field ? `${item.field}: ${item.message}` : item.message;
          }
          return null;
        })
        .filter((m): m is string => m !== null);
      return structuredError(
        "pinch_error",
        messages.length ? messages.join("; ") : `Pinch request failed (HTTP ${status})`,
        { status, body },
      );
    }
  }

  // Fallback: unknown shape.
  return structuredError("pinch_error", `Pinch request failed (HTTP ${status})`, {
    status,
    body,
  });
}

// ── low-level authenticated request ──────────────────────────────────────────

async function pinchRequest<T>(
  env: Env,
  method: string,
  path: string,
  body?: unknown,
): Promise<T | StructuredError> {
  const token = await getToken(env);
  if (typeof token !== "string") return token; // propagate StructuredError

  try {
    const init: RequestInit = {
      method,
      headers: {
        Authorization: `Bearer ${token}`,
        "pinch-version": env.PINCH_VERSION,
        "content-type": "application/json",
      },
    };
    if (body !== undefined) init.body = JSON.stringify(body);

    const res = await fetch(`${env.PINCH_API_BASE}${path}`, init);
    const text = await res.text();
    let parsed: unknown;
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch {
      parsed = { raw: text };
    }

    if (!res.ok) return normalisePinchError(parsed, res.status);
    return parsed as T;
  } catch (err) {
    return structuredError("network_error", `Failed to reach Pinch API (${path})`, {
      cause: String(err),
    });
  }
}

// ── payers / sources ─────────────────────────────────────────────────────────

export interface CreatePayerInput {
  firstName: string;
  emailAddress: string;
  lastName?: string;
  mobileNumber?: string;
}

/** POST /payers — create (or upsert) a payer. */
export function createPayer(
  env: Env,
  input: CreatePayerInput,
): Promise<PinchPayer | StructuredError> {
  return pinchRequest<PinchPayer>(env, "POST", "/payers", input);
}

/** POST /payers/{id} — update a payer's details. */
export function updatePayer(
  env: Env,
  payerId: string,
  patch: Partial<CreatePayerInput>,
): Promise<PinchPayer | StructuredError> {
  return pinchRequest<PinchPayer>(
    env,
    "POST",
    `/payers/${encodeURIComponent(payerId)}`,
    patch,
  );
}

/** GET /payers/{id} — retrieve a payer with embedded sources. */
export function getPayer(
  env: Env,
  payerId: string,
): Promise<PinchPayer | StructuredError> {
  return pinchRequest<PinchPayer>(env, "GET", `/payers/${encodeURIComponent(payerId)}`);
}

/**
 * Resolve which bank-account source to charge for a payer's realtime payment.
 * Pinch's docs say realtime `sourceId` defaults to the payer's default when
 * empty, but the sandbox rejects a source-less realtime charge ("Bank Account
 * required when no token is specified"), so we look one up explicitly:
 * GET the payer and pick the first bank-account source (preferring one that
 * `supportsRealtime`). Returns the src_ id, or a StructuredError if none exists.
 */
export async function resolveBankSourceId(
  env: Env,
  payerId: string,
): Promise<string | StructuredError> {
  const payer = await getPayer(env, payerId);
  if (typeof payer !== "object" || payer === null || "error" in payer) {
    return payer as StructuredError;
  }
  const sources = Array.isArray(payer.sources) ? payer.sources : [];
  const bankSources = sources.filter((s) => s.sourceType === "bank-account");
  // Prefer a realtime-capable, authorised source; fall back to the first bank account.
  const preferred =
    bankSources.find((s) => s.supportsRealtime && s.isAuthorised !== false) ??
    bankSources.find((s) => s.supportsRealtime) ??
    bankSources[0];
  if (!preferred) {
    return structuredError(
      "no_payment_source",
      `Payer "${payerId}" has no bank-account source to charge. Add one with add_bank_account first.`,
      { payerId },
    );
  }
  return preferred.id;
}

export interface CreateBankSourceInput {
  bankAccountName: string;
  bankAccountBsb: string;
  bankAccountNumber: string;
}

/**
 * POST /payers/{id}/sources — attach a bank-account source (the mandate).
 * The caller must mask bankAccountNumber before it ever reaches a log/audit.
 */
export function createBankSource(
  env: Env,
  payerId: string,
  input: CreateBankSourceInput,
): Promise<PinchSource | StructuredError> {
  return pinchRequest<PinchSource>(
    env,
    "POST",
    `/payers/${encodeURIComponent(payerId)}/sources`,
    { sourceType: "bank-account", ...input },
  );
}

// ── payments ─────────────────────────────────────────────────────────────────

export interface CreateScheduledPaymentInput {
  payerId: string;
  amount: number; // integer cents
  transactionDate: string; // YYYY-MM-DD
  description: string;
  sourceId?: string;
}

/** POST /payments — schedule a payment (invoice / plan installment). */
export function createScheduledPayment(
  env: Env,
  input: CreateScheduledPaymentInput,
): Promise<PinchPayment | StructuredError> {
  return pinchRequest<PinchPayment>(env, "POST", "/payments", input);
}

export interface CreateRealtimePaymentInput {
  amount: number; // integer cents
  payerId: string;
  description: string;
  sourceId?: string;
}

/** POST /payments/realtime — charge now. */
export function createRealtimePayment(
  env: Env,
  input: CreateRealtimePaymentInput,
): Promise<PinchPayment | StructuredError> {
  return pinchRequest<PinchPayment>(env, "POST", "/payments/realtime", input);
}

/**
 * DELETE /payments/{id} — cancel a scheduled payment. Pinch returns an empty
 * body on success, so we normalise to `{ ok: true, id }`. A non-2xx comes back
 * as a StructuredError (hard-rule #4).
 */
export async function cancelScheduledPayment(
  env: Env,
  paymentId: string,
): Promise<{ ok: true; id: string } | StructuredError> {
  const res = await pinchRequest<unknown>(
    env,
    "DELETE",
    `/payments/${encodeURIComponent(paymentId)}`,
  );
  if (isStructuredError(res)) return res;
  return { ok: true, id: paymentId };
}

/** GET /payments/{id}. */
export function getPayment(
  env: Env,
  paymentId: string,
): Promise<PinchPayment | StructuredError> {
  return pinchRequest<PinchPayment>(
    env,
    "GET",
    `/payments/${encodeURIComponent(paymentId)}`,
  );
}

// ── list endpoints (mind wrapped vs bare shapes) ─────────────────────────────

/** GET /payments/scheduled — WRAPPED page. */
export function listScheduledPayments(
  env: Env,
  page = 1,
  pageSize = 25,
): Promise<PinchPage<PinchPayment> | StructuredError> {
  return pinchRequest<PinchPage<PinchPayment>>(
    env,
    "GET",
    `/payments/scheduled?page=${page}&pageSize=${pageSize}`,
  );
}

/** GET /payments/payer/{id} — BARE ARRAY of payments. */
export function listPaymentsForPayer(
  env: Env,
  payerId: string,
): Promise<PinchPayment[] | StructuredError> {
  return pinchRequest<PinchPayment[]>(
    env,
    "GET",
    `/payments/payer/${encodeURIComponent(payerId)}`,
  );
}

// ── plans / subscriptions (native recurring payments) ────────────────────────
//
// Verified live against the sandbox (2026-07): a Plan is a reusable schedule
// template; a Subscription binds it to one payer and actually generates the
// individual payment records. `fixedPayments` lets each occurrence carry its
// OWN amountInCents (so create_payment_plan's remainder-on-final-instalment
// split survives exactly — Pinch's `recurringPayment` field only supports a
// single repeating amount, which can't represent that). Cancelling the
// SUBSCRIPTION (DELETE /subscriptions/{id}) removes every not-yet-taken
// payment it generated in one call — confirmed live: the payer's payment list
// was empty immediately after.

export interface PinchFixedPayment {
  amountInCents: number;
  description: string;
  /** Offset from the subscription's startDate, in `scheduledDateInterval` units. */
  scheduledDateOffset: number;
  scheduledDateInterval: "days" | "months" | "years";
  cancelPlanOnFailure?: boolean;
}

export interface PinchPlan {
  id: string;
  name: string;
  fixedPayments?: PinchFixedPayment[];
  subscriberCount?: number;
  requiresTotalAmount?: boolean;
  [k: string]: unknown;
}

/** POST /plans — create a plan (a schedule template with no payer attached yet). */
export function createPlan(
  env: Env,
  input: { name: string; fixedPayments: PinchFixedPayment[] },
): Promise<PinchPlan | StructuredError> {
  return pinchRequest<PinchPlan>(env, "POST", "/plans", input);
}

/**
 * DELETE /plans/{id}. Pinch only allows deleting a plan with zero subscribers,
 * so this is only ever called to clean up a plan whose subscription creation
 * failed (never one already bound to a payer).
 */
export async function deletePlan(
  env: Env,
  planId: string,
): Promise<{ ok: true; id: string } | StructuredError> {
  const res = await pinchRequest<unknown>(env, "DELETE", `/plans/${encodeURIComponent(planId)}`);
  if (isStructuredError(res)) return res;
  return { ok: true, id: planId };
}

export interface PinchSubscription {
  id: string;
  planId: string;
  status?: string;
  fixedPayments?: Array<{ amount?: number; description?: string; transactionDate?: string }>;
  [k: string]: unknown;
}

export interface CreateSubscriptionInput {
  planId: string;
  payerId: string;
  /** YYYY-MM-DD — when the FIRST payment in the plan should run. */
  startDate: string;
  sourceId?: string;
}

/** POST /subscriptions — bind a plan to a payer; Pinch generates the payments. */
export function createSubscription(
  env: Env,
  input: CreateSubscriptionInput,
): Promise<PinchSubscription | StructuredError> {
  return pinchRequest<PinchSubscription>(env, "POST", "/subscriptions", input);
}

/**
 * DELETE /subscriptions/{id} — cancel the whole plan for this payer in ONE
 * call. Pinch removes every not-yet-taken payment generated by it.
 */
export async function cancelSubscription(
  env: Env,
  subscriptionId: string,
): Promise<{ ok: true; id: string } | StructuredError> {
  const res = await pinchRequest<unknown>(
    env,
    "DELETE",
    `/subscriptions/${encodeURIComponent(subscriptionId)}`,
  );
  if (isStructuredError(res)) return res;
  return { ok: true, id: subscriptionId };
}

// ── events / transfers ───────────────────────────────────────────────────────

export interface ListEventsOpts {
  page?: number;
  pageSize?: number;
  eventType?: string;
}

/** GET /events — WRAPPED page. */
export function listEvents(
  env: Env,
  opts: ListEventsOpts = {},
): Promise<PinchPage<PinchEvent> | StructuredError> {
  const { page = 1, pageSize = 25, eventType } = opts;
  const qs = new URLSearchParams({ page: String(page), pageSize: String(pageSize) });
  if (eventType) qs.set("eventType", eventType);
  return pinchRequest<PinchPage<PinchEvent>>(env, "GET", `/events?${qs.toString()}`);
}

/** GET /events/{id}. */
export function getEvent(
  env: Env,
  eventId: string,
): Promise<PinchEvent | StructuredError> {
  return pinchRequest<PinchEvent>(env, "GET", `/events/${encodeURIComponent(eventId)}`);
}

/** GET /transfers/items/{id} — WRAPPED page of transfer line items. */
export function listTransferItems(
  env: Env,
  transferId: string,
  page = 1,
  pageSize = 25,
): Promise<PinchPage<unknown> | StructuredError> {
  return pinchRequest<PinchPage<unknown>>(
    env,
    "GET",
    `/transfers/items/${encodeURIComponent(transferId)}?page=${page}&pageSize=${pageSize}`,
  );
}
